name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Decode and Set Up Keystore
        env:
          ANDROID_NIGHTLY_KEYSTORE: ${{ secrets.ANDROID_NIGHTLY_KEYSTORE }}
        run: |
          echo "$ANDROID_NIGHTLY_KEYSTORE" | base64 --decode > app/nightly.keystore

      - name: Build Nightly APK with Gradle
        env:
          ANDROID_NIGHTLY_KEYSTORE: nightly.keystore
          ANDROID_NIGHTLY_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_NIGHTLY_KEYSTORE_PASSWORD }}
          ANDROID_NIGHTLY_KEYSTORE_ALIAS: ${{ secrets.ANDROID_NIGHTLY_KEYSTORE_ALIAS }}
        run: ./gradlew assembleNightly

      - name: Upload Nightly APK
        uses: actions/upload-artifact@v3
        with:
          name: app-nightly.apk
          path: app/build/outputs/apk/nightly/app-nightly.apk
